### ISSUE TITLE
.expectStatus() does not work for HTTP status 301

### ISSUE THREAD

**Issue by kensteele** [vlucas/frisby#174]
### versions
* frisby@0.8.4
* jasmine-node@1.14.5
* nodejs v0.10.33

### summary
.expectStatus() does not seem to work for HTTP status 301.

### details
The following test results in **Expected 200 to equal 301.** where, the test should pass:
```
var frisby = require('/usr/local/lib/node_modules/frisby');

frisby.create('HTTP status 301')
  .get('http://httpbin.org/status/301')
    .expectStatus(301)
.toss()
```
output:
```
$ jasmine-node links_spec.js 
F

Failures:

  1) Frisby Test: Ensure we are dealing with a teapot 
	[ GET http://httpbin.org/status/301 ]
   Message:
     Expected 200 to equal 301.
   Stacktrace:
     Error: Expected 200 to equal 301.
    at null.<anonymous> (/usr/local/lib/node_modules/frisby/lib/frisby.js:491:42)
    at null.<anonymous> (/usr/local/lib/node_modules/frisby/lib/frisby.js:1072:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Finished in 0.642 seconds
1 test, 1 assertion, 1 failure, 0 skipped
```
Curl output from the same URL:
```
$ curl -I http://httpbin.org/status/301
HTTP/1.1 301 MOVED PERMANENTLY
Connection: keep-alive
Server: gunicorn/18.0
Date: Wed, 31 Dec 2014 01:17:26 GMT
Location: /redirect/1
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Length: 0
Via: 1.1 vegur
```

The following nodejs code correctly produces the expected 301 status:
```
var http = require('http');

http.get("http://httpbin.org/status/301", function(res) {
  console.log("Got response: " + res.statusCode);
});
```
output:
```
$ node get.js 
Got response: 301
```

**Comment by ArkeologeN** [comment]
Any update? I am facing the same issue with 301 / 302 redirect?

**Comment by olivierdeckers** [comment]
Frisby follow redirects by default. To prevent this behaviour, set the followRedirect parameter to false:

```
frisby.create('HTTP status 301')
  .get('http://httpbin.org/status/301', {followRedirect: false})
    .expectStatus(301)
.toss()
```

**Comment by pasindud** [comment]
I belive ```followRedirect``` comes from the npm request package, which has stuff like ```maxRedirects``` ,  ```followAllRedirects``` https://www.npmjs.com/package/request

**Comment by vlucas** [comment]
Did this solve your issue?

**Comment by kensteele** [comment]
Yes it did, thanks!
