### ISSUE TITLE
Expected 'undefined' to be type 'array' on key 'data'

### ISSUE THREAD

**Issue by igvenkatesh** [vlucas/frisby#249]
I am getting for error when i am sending a array of json objects in post request below

```
frisby.create('testing array')
                             .post(URL , [{
                                 "Id":1,
                                 "question": 'test question?',
                                 "answer": 'test answer'
                             }])
                             .inspectRequest()
                             .expectStatus(200)
                             .expectHeaderContains('Content-Type', 'application/json')
                             .inspectJSON()
                             .expectJSONTypes({
                                 data: Array
                             })                            
                                 .toss()

```
and getting this error in response 

Error: Expected 'undefined' to be type 'array' on key 'data'

**Comment by ctadeu** [comment]
can you post the output for the inpectJSON() ?

**Comment by igvenkatesh** [comment]
{ code: 400,
  message: 'Unable to process JSON',
  details: null }
 but this request post request provides 200 response code in postman

**Comment by ctadeu** [comment]
looks like your post request is wrong. your request should be a json not an array.
```javascript
frisby.create('testing array')
   .post(URL , { "Id":1, "question": 'test question?', "answer": 'test answer'})
   .inspectRequest()
   .expectStatus(200)
   .expectHeaderContains('Content-Type', 'application/json')
   .inspectJSON()
   .expectJSONTypes({ data: Array})                            
 .toss();

**Comment by igvenkatesh** [comment]
i tried it in postman and it is working fine.  with [] brackets

**Comment by igvenkatesh** [comment]
i have one more small query - ["test'] changed ['test'] when sending in post request. in frisby

**Comment by ctadeu** [comment]
can you add  { json: true } ?

```javascript
frisby.create('testing array')
   .post(URL , { "Id":1, "question": 'test question?', "answer": 'test answer'}, { json: true } )
   .inspectRequest()
   .expectStatus(200)
   .expectHeaderContains('Content-Type', 'application/json')
   .inspectJSON()
   .expectJSONTypes({ data: Array})                            
 .toss();

**Comment by igvenkatesh** [comment]
I am getting this error when i use json:true for the array request 

 Message:
     Error: Error parsing JSON string: Unexpected token u
	Given: undefined
``` 
  Stacktrace:
     Error: Error parsing JSON string: Unexpected token u
	Given: undefined
    at _jsonParse (/home/application/Venkatesh/Boss-testscripts/scripts/node_modules/frisby/lib/frisby.js:1219:11)
    at null.<anonymous> (/home/application/Venkatesh/Boss-testscripts/scripts/node_modules/frisby/lib/frisby.js:562:20)
    at null.<anonymous> (/home/application/Venkatesh/Boss-testscripts/scripts/node_modules/frisby/lib/frisby.js:1074:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

```

**Comment by ctadeu** [comment]
humm, i will try to find a service which use this array, and test. but maybe it not support by frisby

if you know any public service similar to yours let me know

**Comment by igvenkatesh** [comment]
Thanks Carlos , But i found that in Issue number 159 that frisby supports array - can you please confirm.

**Comment by igvenkatesh** [comment]
actually the service was not providing as json in the response and i was inspecting that json so closing this issue.
