### ISSUE TITLE
["test"] gets changed to ['test] when send in a post request

### ISSUE THREAD

**Issue by igvenkatesh** [vlucas/frisby#250]
I have below script to test above scenario
```
frisby.create('add permissions to  roles by id')
                         .post(URL,
                         	["test"],{
                     json: true
              			   })
                         .inspectRequest()
                         .expectStatus(201)
                         .expectHeaderContains('Content-Type', 'application/json')
                         .inspectJSON()

```
In the response - for .inpsectRequest - i am getting ['test'] instead of ["test"]

and also getting this error : 

```
Error: Error parsing JSON string: Unexpected token u
	Given: undefined
   Stacktrace:
     Error: Error parsing JSON string: Unexpected token u
	Given: undefined
    at _jsonParse (/home/application/Venkatesh/Boss-testscripts/scripts/node_modules/frisby/lib/frisby.js:1219:11)
    at null.<anonymous> (/home/application/Venkatesh/Boss-testscripts/scripts/node_modules/frisby/lib/frisby.js:562:20)
    at null.<anonymous> (/home/application/Venkatesh/Boss-testscripts/scripts/node_modules/frisby/lib/frisby.js:1074:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by igvenkatesh** [comment]
this is not an issue . Closing this issue.
