### ISSUE TITLE
One Object in an Array doesn't work with custom callback

### ISSUE THREAD

**Issue by dimastopel** [vlucas/frisby#296]
I am new to frisby so I might missing something. 

This is the code. If I use option num 1 everything works as expected. If I use option num 2 the test fails with the reason that there are other object that fail this test. 

Why does it test other objects it it found one that complies? Is there are better way to achieve this?

``` javascript
var frisby = require('frisby');

frisby.create('Some test')
.get('http://localhost:8081/api/v1/test/items')
.addHeader('Authorization', 'Basic <SOMETOKEN>')
.expectStatus(200)
.expectHeaderContains('content-type', 'application/json')
.expectJSON('?', {
    /*option #1*/ _id: '5e1cacd7f242d10101f9ee40'
    /*option #2*/ //_id: function(val) { expect(val).toContain("ee40"); }
})
.toss();
```

Thank you

**Comment by ctadeu** [comment]
Hello, I dont use the '?' in my case and all it work

````
.expectJSON({
    	files: function(val) {
    	expect(val).toEqual([])
	},
	origin: 'user',
	schema: function(val) {
		expect(val).toEqual({})
	}
})

what error are you getting?

**Comment by dimastopel** [comment]
Well, I get back an array of items and I'd like to find one that has `_id` that contains some sub-string. As I understand this is exactly what `'?'` is for. 

This is the `jamine-node` output in case of an error (option 2):

```
$ jasmine-node --verbose .

Frisby Test: Test Images API - 67 ms
    
	[ GET http://localhost:8081/api/v1/test/items ] - 65 ms

Failures:

  1) Frisby Test: Test Images API 
	[ GET http://localhost:8081/api/v1/test/items ]
   Message:
     Expected '569ccbb2f242d10100f9ee10' to contain 'ee40'.
   Stacktrace:
     Error: Expected '569ccbb2f242d10100f9ee10' to contain 'ee40'.
    at frisby.create.get.addHeader.expectStatus.expectHeaderContains.expectJSON._id (/home/dima/dev/tw_api_test/apitest_spec.js:11:38)
    at _jsonContains (/home/dima/node_modules/frisby/lib/frisby.js:1258:35)
    at null.<anonymous> (/home/dima/node_modules/frisby/lib/frisby.js:699:24)
    at null.<anonymous> (/home/dima/node_modules/frisby/lib/frisby.js:1074:43)

  2) Frisby Test: Test Images API 
	[ GET http://localhost:8081/api/v1/test/items ]
   Message:
     Expected '569ccbb6f242d10100f9ee1c' to contain 'ee40'.
   Stacktrace:
     Error: Expected '569ccbb6f242d10100f9ee1c' to contain 'ee40'.
    at frisby.create.get.addHeader.expectStatus.expectHeaderContains.expectJSON._id (/home/dima/dev/tw_api_test/apitest_spec.js:11:38)
    at _jsonContains (/home/dima/node_modules/frisby/lib/frisby.js:1258:35)
    at null.<anonymous> (/home/dima/node_modules/frisby/lib/frisby.js:699:24)
    at null.<anonymous> (/home/dima/node_modules/frisby/lib/frisby.js:1074:43)

  3) Frisby Test: Test Images API 
	[ GET http://localhost:8081/api/v1/test/items ]
   Message:
     Expected '569ccbf6f242d10100f9ee42' to contain 'ee40'.
   Stacktrace:
     Error: Expected '569ccbf6f242d10100f9ee42' to contain 'ee40'.
    at frisby.create.get.addHeader.expectStatus.expectHeaderContains.expectJSON._id (/home/dima/dev/tw_api_test/apitest_spec.js:11:38)
    at _jsonContains (/home/dima/node_modules/frisby/lib/frisby.js:1258:35)
    at null.<anonymous> (/home/dima/node_modules/frisby/lib/frisby.js:699:24)
    at null.<anonymous> (/home/dima/node_modules/frisby/lib/frisby.js:1074:43)

Finished in 0.069 seconds
1 test, 6 assertions, 3 failures, 0 skipped

```

**Comment by ctadeu** [comment]
I dont think in this case it will iterate automatically over all items in the array. Maybe you need create some code to deal with that. also you can add some console.log to check if this is iterating or just getting the first item.

**Comment by dimastopel** [comment]
It is iterating. See how all the items are printed in the output above. I'd expect it to stop iterating once a "matching" item is found (and pass the test), but it just continues.

**Comment by ctadeu** [comment]
im trying to check in my spare time.

**Comment by ctadeu** [comment]
can you try what is decribe here? https://github.com/vlucas/frisby/issues/280

**Comment by dimastopel** [comment]
I did try this. Did not help. Thanks!

sent from my mobile

**Comment by ctadeu** [comment]
change the expectJSON  to expectJSONContains

**Comment by dimastopel** [comment]
I don't have such a function...

```
$ jasmine-node .
Exception loading: /home/user/dev/api_test/apitest_spec.js
[TypeError: undefined is not a function]
```

There is `expectBodyContains` but it doesn't parse JSON AFAIU.

**Comment by ctadeu** [comment]
:(

**Comment by vlucas** [comment]
Please try this in v2. It should be much more stable.
