### ISSUE TITLE
expect('json') more strict on structure than expectJSON() was

### ISSUE THREAD

**Issue by bkimminich** [vlucas/frisby#365]
## v0
```
frisby.create('gets existing basket by id')
  .addHeaders(authHeader)
  .get(REST_URL + '/basket/1')
  .expectStatus(200)
  .expectHeaderContains('content-type', 'application/json')
  .expectJSON('data', {id: 1})
  .toss()
```
works just fine.

## v2
```
  it('gets existing basket by id', function (done) {
    frisby.get(REST_URL + '/basket/1', {headers: authHeader})
      .expect('status', 200)
      .expect('header', 'content-type', /application\/json/)
      .expect('json', 'data', {id: 1})
      .done(done)
  })
```
fails with
```
Message:
     Expected 'AssertionError: { id: 1 } deepEqual { id: 1,
  coupon: null,
  createdAt: '2017-07-26T12:52:01.000Z',
  updatedAt: '2017-07-26T12:52:01.000Z',
  UserId: 1,
  produc
    at jsonAssertion (C:\Data\Github\juice-shop\node_modules\frisby\src\frisby\expects.js:68:14)
    at Object.withPath (C:\Data\Github\juice-shop\node_modules\frisby\src\frisby\utils.js:68:12)
    at FrisbySpec.json (C:\Data\Github\juice-shop\node_modules\frisby\src\frisby\expects.js:67:11)
    at FrisbySpec._addExpect (C:\Data\Github\juice-shop\node_modules\frisby\src\frisby\spec.js:385:23)
    at then (C:\Data\Github\juice-shop\node_modules\frisby\src\frisby\spec.js:290:26)
    at _fetch._fetch.then (C:\Data\Github\juice-shop\node_modules\frisby\src\frisby\spec.js:222:18)
    at process._tickCallback (internal/process/next_tick.js:109:7)' to be null.
```
### v2 (workaround)
```
  it('gets existing basket with contained products by id', function (done) {
    frisby.get(REST_URL + '/basket/1', {headers: authHeader})
      .expect('status', 200)
      .expect('header', 'content-type', /application\/json/)
      .then(function (json) {
        expect(json.data.id).toBe(1)
      })
      .done(done)
  })
```
fails as well, because what is supposed to be the JSON in the `json` param is instead:
```
FrisbyResponse {
  _response:
   Body {
     url: 'http://localhost:3000/rest/basket/1',
     status: 200,
     statusText: 'OK',
     headers: Headers { _headers: [Object] },
     ok: true,
     body:
      PassThrough {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     bodyUsed: true,
     size: 0,
     timeout: 5000,
     _raw: [ <Buffer 7b 22 73 74 61 74 75 73 22 3a 22 73 75 63 63 65 73 73 22 2c 22 64 61 74 61 22 3a 7b 22 69 64 22 3a 31 2c 22 63 6f 75 70 6f 6e 22 3a 6e 75 6c 6c 2c 22 ... > ],
     _abort: false,
     _bytes: 1289 },
  _body:
   { status: 'success',
     data:
      { id: 1,
        coupon: null,
        createdAt: '2017-07-26T12:48:41.000Z',
        updatedAt: '2017-07-26T12:48:41.000Z',
        UserId: 1,
        products: [Object] } } }
```

I would prefer if `expect('json')` would work like `expectJSON()` did, but if that's not intended I need at least the workaround to work <or> a hint how to implement the test correctly in _v2-style_... :-)

**Comment by bkimminich** [comment]
### v2 (another - actually working - workaround)

Obviously this shenanigans works, but it contradicts the documentation:

```
  it('gets existing basket with contained products by id', function (done) {
    frisby.get(REST_URL + '/basket/1', {headers: authHeader})
      .expect('status', 200)
      .expect('header', 'content-type', /application\/json/)
      .then(function (res) {
        expect(res._body.data.id).toBe(1)
        expect(res._body.data.products.length).toBe(3)
      })
      .done(done)
  })
```

It would be really nice if the JSON data would be accessible like the documentation promises but you still leave in the option to do things with the `FrisbyResponse` directly if necessary.

**Comment by bkimminich** [comment]
### v2 (the best working workaround so far)
It's just syntactic sugarcoating but it looks a lot better that the `_body` from above snippet:
```
  it('gets existing basket with contained products by id', function (done) {
    frisby.get(REST_URL + '/basket/1', {headers: authHeader})
      .expect('status', 200)
      .expect('header', 'content-type', /application\/json/)
      .then(function (res) {
        expect(res.json.data.id).toBe(1)
        expect(res.json.data.products.length).toBe(3)
      })
      .done(done)
  })
```

**Comment by vlucas** [comment]
Yes, I switched Frisby v2 over to a FrisbyResponse object since Promise functions can only accept a single argument, and there might be more data you want to custom test.

**Comment by vlucas** [comment]
What would you think about two separate 'json' expectations, like 'json', and 'jsonStrict'?

**Comment by bkimminich** [comment]
* :+1:  for having `json` and `jsonStrict`! That actually prevents a lot of unnecessary `.then()`'s for me
* :+1: when a `.then()` is unavoidable, I think it's fine as it is with `FrisbyResponse.json()` available. The docs just need to reflect that then.

**Comment by vlucas** [comment]
Okay. I will add a separate 'jsonStrict' call then.

Also, you can add your own custom expectations with `frisby.addExpectHandler` - see [the README section](https://github.com/vlucas/frisby#define-custom-expect-handlers).

**Comment by vlucas** [comment]
I just looked into this, and there actually is a `json` (strict) as well as a `jsonContains` (loose) expect handler. So I guess this would just be a re-name.

**Comment by vlucas** [comment]
I actually think I should make the change, because I want both `json` and `jsonTypes` to be consistent. This way, the defaults are loose (extra keys are not errors), and we can also have `jsonStrict` and `jsonTypesStrict` that are strict. Most people will want the looser matchers to only check for specific keys, and I want v2 to be as noob-friendly as possible.
