### ISSUE TITLE
Cant run tests at frisby v2, even with new node.js installed

### ISSUE THREAD

**Issue by alexevenly** [vlucas/frisby#370]
+ jasmine-node Tests/RestApiTests/spec/catalog_calls_check_spec.js --junitreport /tmp/circle-artifacts.DYKSooQ/frisbyjs_output
creating junit xml report save path: ./reports/
Exception loading: /home/ubuntu/QA-Automation/Tests/RestApiTests/spec/catalog_calls_check_spec.js
TypeError: frisby.create is not a function
    at Object.<anonymous> (/home/ubuntu/QA-Automation/Tests/RestApiTests/spec/catalog_calls_check_spec.js:147:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.jasmine.executeSpecsInFolder (/opt/circleci/nodejs/v6.9.1/lib/node_modules/jasmine-node/lib/jasmine-node/index.js:160:9)
    at Object.<anonymous> (/opt/circleci/nodejs/v6.9.1/lib/node_modules/jasmine-node/lib/jasmine-node/cli.js:248:9)

**Comment by alexevenly** [comment]
Or is there a way to install previous version of frsiby? (with npm)

**Comment by vlucas** [comment]
When I published v2, I had a feeling this might happen. Your `frisby` version was not locked to `0.8.5`, so you got the brand new `2.0.0`. I just released version `2.0.1` with this addition to serve as a helpful error for others who hit this same issue:

https://github.com/vlucas/frisby/commit/90e5f0969dc352a4e87d65c85759eb335f948bba#diff-8d9b517f32c18a1d216b0ec18d92252fR41
