### ISSUE TITLE
Array comparisons do not work

### ISSUE THREAD

**Issue by tkeffer** [vlucas/frisby#395]
I cannot get the new V2.x API to work when testing against a JSON array. It's quite possible I'm doing something wrong, but I've exhausted everything I can think of. 

However, I am able to get the array test to work by using the Jasmine `expect` function.

Here's a script that runs two specs, using a public "minor planets" RESTful API. The first spec uses the builtin Frisby `expect`, the second the Jasmine `expect` function.

```javascript
const frisby = require('frisby');

const expected_value = [
    {
        rms: 0.6,
        epoch: 'K1794',
        readable_des: '(1) Ceres',
        H: 3.34,
        num_obs: 6672,
        ref: 'MPO399990',
        G: 0.12,
        last_obs: '20170305',
        comp: 'MPCLINUX  ',
        M: 309.49412,
        U: ' ',
        e: 0.0756074,
        a: 2.7674094,
        om: 80.30888,
        pert_p: '30h',
        d: 0.21408881,
        i: 10.59322,
        des: '00001',
        flags: '0000',
        num_opp: 113,
        w: 73.02368,
        pert_c: 'M-v'
    },
    {
        rms: 0.58,
        epoch: 'K1794',
        readable_des: '(2) Pallas',
        H: 4.13,
        num_obs: 7877,
        ref: 'MPO410073',
        G: 0.11,
        last_obs: '20170601',
        comp: 'MPCLINUX  ',
        M: 291.65136,
        U: ' ',
        e: 0.2305974,
        a: 2.7730852,
        om: 173.08718,
        pert_p: '28h',
        d: 0.21343186,
        i: 34.83792,
        des: '00002',
        flags: '0000',
        num_opp: 108,
        w: 309.99154,
        pert_c: 'M-v'
    },
    {
        rms: 0.59,
        epoch: 'K1794',
        readable_des: '(3) Juno',
        H: 5.33,
        num_obs: 6863,
        ref: 'MPO410073',
        G: 0.32,
        last_obs: '20170521',
        comp: 'MPCLINUX  ',
        M: 259.23491,
        U: ' ',
        e: 0.2568534,
        a: 2.6685312,
        om: 169.85828,
        pert_p: '38h',
        d: 0.22609744,
        i: 12.98996,
        des: '00003',
        flags: '0000',
        num_opp: 104,
        w: 248.20648,
        pert_c: 'M-v'
    }
];

// First run a spec using the built in Frisby 'expect'. This fails.
it("should work for a 'JSON' field", function (doneFn) {
    frisby
        .get('http://www.asterank.com/api/mpc?limit=3')
        .expect('status', 200)
        .expect('json', '', expected_value)
        .done(doneFn);
});

// Now run a spec using Jasmine's expect. This works
it("should work for a Jasmine 'expect' clause", function (doneFn) {
    frisby
        .get('http://www.asterank.com/api/mpc?limit=3')
        .expect('status', 200)
        .then(function (res) {
            expect(res.body).toEqual(expected_value);
        })
        .done(doneFn);
});
```

Here's the output from the script:

```shell
$ jasmine spec/server/array_spec.js
Started
F.

Failures:
1) should work for a 'JSON' field
  Message:
    Failed: Response [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ] does not contain provided JSON [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ]
  Stack:
    AssertionError: Response [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ] does not contain provided JSON [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ]
        at jsonContainsAssertion (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/expects.js:79:14)
        at Object.withPath (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/utils.js:11:12)
        at FrisbySpec.json (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/expects.js:70:11)
        at FrisbySpec._addExpect.e (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/spec.js:408:23)
        at then (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/spec.js:299:26)
        at _fetch._fetch.then (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/spec.js:231:18)
        at process._tickCallback (internal/process/next_tick.js:103:7)

2 specs, 1 failure
Finished in 0.742 seconds
```
Again, it's entirely possible I'm doing something wrong. In particular, perhaps the semantics of the `path` argument has changed?

**Comment by tkeffer** [comment]
Here's a slightly simpler, and better version. This one first fetches the first 3 elements, then uses them as the expected value. This makes it kind of an identity test. It's less sensitive to changes in the asteroid database.

```javascript
const frisby = require('frisby');

var expected_value;

it("should first fetch the first 3 asteroids", function(doneFn){
    frisby
        .get('http://www.asterank.com/api/mpc?limit=3')
        .expect('status', 200)
        .then(function (res) {
            expected_value = res.body;
        })
        .done(doneFn);
})

// Now run a spec using the built in Frisby 'expect'. This fails.
it("should work for a 'JSON' field", function (doneFn) {
    frisby
        .get('http://www.asterank.com/api/mpc?limit=3')
        .expect('status', 200)
        .expect('json', '', expected_value)
        .done(doneFn);
});

// Now run a spec using Jasmine's expect. This works
it("should work for a Jasmine 'expect' clause", function (doneFn) {
    frisby
        .get('http://www.asterank.com/api/mpc?limit=3')
        .expect('status', 200)
        .then(function (res) {
            expect(res.body).toEqual(expected_value);
        })
        .done(doneFn);
});
```

**Comment by vlucas** [comment]
Try using:
```javascript
.expect('json', '0', expected_value)
```

**Comment by tkeffer** [comment]
> Are you trying to match the exact, full object?

Yes, the full array. This was possible on Frisby v0.85.

> Try using a numeric path for the first item:

Yes, that works, but, of course, you're only matching the first item. I need to match them all. That is, the whole array.

**Comment by vlucas** [comment]
Try using it without a path:

```javascript
.expect('json', expected_value)
```

**Comment by tkeffer** [comment]
That was the very first thing I tried. Didn't work. Here's the output:

```shell
Started
.F.

Failures:
1) should work for a 'JSON' field
  Message:
    Failed: Response [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ] does not contain provided JSON [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ]
  Stack:
    AssertionError: Response [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ] does not contain provided JSON [ [{"rms":0.6,"epoch":"K1794","readable_des":"(1) Ceres","H":3.34,"num_obs":6672,"ref":"MPO399990","G":0.12,"last_obs":"20170305","comp":"MPCLINUX  ","M":309.49412,"U":" ","e":0.0756074,"a":2.7674094,"om":80.30888,"pert_p":"30h","d":0.21408881,"i":10.59322,"des":"00001","flags":"0000","num_opp":113,"w":73.02368,"pert_c":"M-v"},{"rms":0.58,"epoch":"K1794","readable_des":"(2) Pallas","H":4.13,"num_obs":7877,"ref":"MPO410073","G":0.11,"last_obs":"20170601","comp":"MPCLINUX  ","M":291.65136,"U":" ","e":0.2305974,"a":2.7730852,"om":173.08718,"pert_p":"28h","d":0.21343186,"i":34.83792,"des":"00002","flags":"0000","num_opp":108,"w":309.99154,"pert_c":"M-v"},{"rms":0.59,"epoch":"K1794","readable_des":"(3) Juno","H":5.33,"num_obs":6863,"ref":"MPO410073","G":0.32,"last_obs":"20170521","comp":"MPCLINUX  ","M":259.23491,"U":" ","e":0.2568534,"a":2.6685312,"om":169.85828,"pert_p":"38h","d":0.22609744,"i":12.98996,"des":"00003","flags":"0000","num_opp":104,"w":248.20648,"pert_c":"M-v"}] ]
        at jsonContainsAssertion (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/expects.js:79:14)
        at Object.withPath (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/utils.js:11:12)
        at FrisbySpec.json (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/expects.js:70:11)
        at FrisbySpec._addExpect.e (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/spec.js:408:23)
        at then (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/spec.js:299:26)
        at _fetch._fetch.then (/home/tkeffer/git/tkeffer/weert-js/node_modules/frisby/src/frisby/spec.js:231:18)
        at process._tickCallback (internal/process/next_tick.js:103:7)

3 specs, 1 failure
Finished in 2.003 seconds
```

Give the script a try yourself. It's standalone. It requires only Jasmine (and Frisby)

**Comment by H1Gdev** [comment]
@vlucas 
I think verifying the array is a very difficult problem...
But fix only this issue, change expect **json** method like following.

src/frisby/expects.js
```diff
@@ -70,12 +70,15 @@ const expects = {
     utils.withPath(path, response._body, function jsonContainsAssertion(jsonChunk) {
       let failMsg = "Response [ " + JSON.stringify(jsonChunk) + " ] does not contain provided JSON [ " + JSON.stringify(json) + " ]";

-      if (_.isObject(json)) {
-        // Object/aray test
-        assert.ok(_.some([jsonChunk], json), failMsg);
-      } else {
-        // Single value test
+      try {
         assert.equal(jsonChunk, json);
+      } catch (e) {
+        if (_.isObject(json)) {
+          // Object test
+          assert.ok(_.some([jsonChunk], json), failMsg);
+        } else {
+          throw e;
+        }
       }
     });
   },
````
