### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by SlickNutter** [vlucas/frisby#409]
Could it be that frisby mishandles 204 No content responses?

In this case there is an error, even though a 204 is returned. Could it be that in fromJSON it isn't checked whether the response status is 204 and tries to get the response body without checking?

My test:
```
    it('aaa', (done) => {
        let deleteUrl = 'http://127.0.0.1:3000/api/program/projects/1/days/7';
        frisby.del(deleteUrl)
            .then((response) => {
                // logging and writing response to a file
            }).done(done);
    });
```

console output:
```
 FAIL  __tests__\days-crud.spec.js
  ● Console

    console.log __tests__\days-crud.spec.js:75
      FrisbyResponse {
        _response:
         Body {
           url: 'http://127.0.0.1:3000/api/program/projects/1/days/7',
           status: 204,
           statusText: 'No Content',
           headers: Headers { _headers: [Object] },
           ok: true,
           body:
            PassThrough {
              _readableState: [Object],
              readable: false,
              domain: null,
              _events: [Object],
              _eventsCount: 4,
              _maxListeners: undefined,
              _writableState: [Object],
              writable: false,
              allowHalfOpen: true,
              _transformState: [Object] },
           bodyUsed: true,
           size: 0,
           timeout: 5000,
           _raw: [],
           _abort: false,
           _bytes: 0 } }

  ● Day CRUD › aaa

    Failed: undefined is not a correct value

      at stackFormatter (node_modules/jest-jasmine2/build/expectation_result_factory.js:49:427)
      at FrisbySpec._fetchErrorHandler (node_modules/frisby/src/frisby/spec.js:279:7)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Day CRUD › aaa

    FetchError: invalid json response body at http://127.0.0.1:3000/api/program/projects/1/days/7 reason: Unexpected end of JSON input

      at node_modules/node-fetch/lib/body.js:48:31
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


Test Suites: 1 failed, 2 skipped, 1 of 3 total
Tests:       1 failed, 4 skipped, 5 total
Snapshots:   0 total
Time:        1.718s
Ran all test suites.
```

response:
```
{
    "_response": {
        "url": "http://127.0.0.1:3000/api/program/projects/1/days/7",
        "status": 204,
        "statusText": "No Content",
        "headers": {
            "_headers": {
                "vary": [
                    "Origin, Accept-Encoding"
                ],
                "access-control-allow-credentials": [
                    "true"
                ],
                "x-xss-protection": [
                    "1; mode=block"
                ],
                "x-frame-options": [
                    "DENY"
                ],
                "x-download-options": [
                    "noopen"
                ],
                "x-content-type-options": [
                    "nosniff"
                ],
                "content-type": [
                    "application/json"
                ],
                "date": [
                    "Wed, 18 Oct 2017 13:19:58 GMT"
                ],
                "connection": [
                    "close"
                ]
            }
        },
        "ok": true,
        "body": {
            "_readableState": {
                "objectMode": false,
                "highWaterMark": 16384,
                "buffer": {
                    "head": null,
                    "tail": null,
                    "length": 0
                },
                "length": 0,
                "pipes": null,
                "pipesCount": 0,
                "flowing": true,
                "ended": true,
                "endEmitted": true,
                "reading": false,
                "sync": false,
                "needReadable": false,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "destroyed": false,
                "defaultEncoding": "utf8",
                "awaitDrain": 0,
                "readingMore": false,
                "decoder": null,
                "encoding": null
            },
            "readable": false,
            "domain": null,
            "_events": {},
            "_eventsCount": 4,
            "_writableState": {
                "objectMode": false,
                "highWaterMark": 16384,
                "finalCalled": false,
                "needDrain": false,
                "ending": true,
                "ended": true,
                "finished": true,
                "destroyed": false,
                "decodeStrings": true,
                "defaultEncoding": "utf8",
                "length": 0,
                "writing": false,
                "corked": 0,
                "sync": true,
                "bufferProcessing": false,
                "writecb": null,
                "writelen": 0,
                "bufferedRequest": null,
                "lastBufferedRequest": null,
                "pendingcb": 0,
                "prefinished": true,
                "errorEmitted": false,
                "bufferedRequestCount": 0,
                "corkedRequestsFree": {
                    "next": null,
                    "entry": null
                }
            },
            "writable": false,
            "allowHalfOpen": true,
            "_transformState": {
                "needTransform": false,
                "transforming": false,
                "writecb": null,
                "writechunk": null,
                "writeencoding": null
            }
        },
        "bodyUsed": true,
        "size": 0,
        "timeout": 5000,
        "_raw": [],
        "_abort": false,
        "_bytes": 0
    }
}
```

**Comment by vlucas** [comment]
Might be. Can you check with http://httpbin.org/status/204 and see what happens?

**Comment by vlucas** [comment]
I just added some tests for this case, and Frisby appears to handle this correctly. Are you sending a 204 response and actually still outputting a body? (check `response.body`)

**Comment by SlickNutter** [comment]
`console.log(response.body)` returns `undefined`.

When writting the response of:
http://httpbin.org/status/204
the JSON has a `"_body"` property that isn't present in my APIs response but the call is handled errorless by Frisby.

Maybe an empty `_body` needs to be explicitelly returned?

**Comment by SlickNutter** [comment]
Went through the code and saw that at frisby/response.js in the constructor you dont check when you have  a 204 that "_body" has a certain value that you can rely.

I'd propose somethign along the lines of:
```
  constructor(fetchResponse) {
    if (fetchResponse.status === 204 && !fetchResponse._body)
        fetchResponse._body = "";
    this._response = fetchResponse;
  }
```

**Comment by SlickNutter** [comment]
Found the problem, even though no content is returned by the API, our `Content-Type` is set to `application/json` https://github.com/vlucas/frisby/blob/661595bc93274d34c0a452a1f7ff6d9afe9409e8/src/frisby/spec.js#L135

Then `response.json()` is called
https://github.com/vlucas/frisby/blob/661595bc93274d34c0a452a1f7ff6d9afe9409e8/src/frisby/spec.js#L136
where ultimately the error occurs because _body is empty.

**Comment by vlucas** [comment]
I see. Thanks for digging in on this one. Seems like an explicit check for `204` status is going to be needed. If you want to submit a PR, I will merge it in for you. Otherwise, I will have some time to get to this next week.
