### ISSUE TITLE
Unhandled promise rejection for embedded frisby calls

### ISSUE THREAD

**Issue by ingshtrom** [vlucas/frisby#416]
In the example docs in the README.md, there is this:
```
it('should return all posts and first post should have comments', function (done) {
    frisby.get('http://jsonplaceholder.typicode.com/posts')
      .expect('status', 200)
      .expect('jsonTypes', '*', {
        userId: Joi.number(),
        id: Joi.number(),
        title: Joi.string(),
        body: Joi.string()
      })
      .then(function (res) { // res = FrisbyResponse object
        let postId = res.json[0].id;

        // Get first post's comments
        // RETURN the FrisbySpec object so the 'done' function waits on it to finish - just like a Promise chain
        return frisby.get('http://jsonplaceholder.typicode.com/posts/' + postId + '/comments')
          .expect('status', 200)
          .expect('json', '*', {
            postId: postId
          })
          .expect('jsonTypes', '*', {
            postId: Joi.number(),
            id: Joi.number(),
            name: Joi.string(),
            email: Joi.string().email(),
            body: Joi.string()
          });
      })
      .done(done);
  });
```

That works well, but an error would actually cause an `Unhandled promise rejection` error and you get zero stack traces. For example, look at this test where we change `name: Joi.string(),` to `name: Joi.number(),`. Here is the test:
```
it('should return all posts and first post should have comments', function (done) {
    frisby.get('http://jsonplaceholder.typicode.com/posts')
      .expect('status', 200)
      .expect('jsonTypes', '*', {
        userId: Joi.number(),
        id: Joi.number(),
        title: Joi.string(),
        body: Joi.string()
      })
      .then(function (res) { // res = FrisbyResponse object
        let postId = res.json[0].id;

        // Get first post's comments
        // RETURN the FrisbySpec object so the 'done' function waits on it to finish - just like a Promise chain
        return frisby.get('http://jsonplaceholder.typicode.com/posts/' + postId + '/comments')
          .expect('status', 200)
          .expect('json', '*', {
            postId: postId
          })
          .expect('jsonTypes', '*', {
            postId: Joi.number(),
            id: Joi.number(),
            name: Joi.number(), // <------------------------ HERE!
            email: Joi.string().email(),
            body: Joi.string()
          });
      })
      .done(done);
  });
```

Here is the output: 
![image](https://user-images.githubusercontent.com/571756/32228784-99e3f97a-be25-11e7-80fb-3ca6072d6dd8.png)

Here is the exact version of Frisby that I am using: 
![image](https://user-images.githubusercontent.com/571756/32228871-d121ab9e-be25-11e7-8baa-2693380ff4f6.png)

I expect chained/embedded promises to work, but they don't, as shown above. Of course I could manually fix this by adding a callback to the `.catch()` function, but that is painful as the test suite grows.

Is this a known bug?

**Comment by H1Gdev** [comment]
@ingshtrom 
from output.
` FAIL  routes/__tests__/account.integ.js (7.049s)`

`    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

Timeout has occurred.

So, set Jasmine timeout in either way.(default: 5[ms])

- set jasmine.DEFAULT_TIMEOUT_INTERVAL.
- set 3rd argument in it().

https://jasmine.github.io/api/2.6/global.html#it

**Comment by lysium** [comment]
Doesn't the timeout occur because frisby does not handle the rejected promise (and thus never returns to have jasmine's done function called)?

I just ran into the same issue.

**Comment by ingshtrom** [comment]
@lysium exactly. The timeout is only a side effect of the real problem, from what I can tell. The real problem is that the error is not caught in the test runner or frisby.

**Comment by H1Gdev** [comment]
@lysium 
@ingshtrom 
Even if you extend timeout, will situation not improve ?

In my test environment this approach has been improved.

**Result**
_Timeout not specified_
```
> test@1.0.0 test
> jest

 FAIL  __tests__/api.spec.js (5.477s)
  Posts
    ? should return all posts and first post should have comments (5012ms)

  ● Posts ? should return all posts and first post should have comments

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.974s, estimated 6s
Ran all test suites.
(node:6825) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ValidationError: child "name" fails because ["name" must be a number]
(node:6825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! Test failed.  See above for more details.
```

_Timeout specified_
```
> test@1.0.0 test
> jest

 FAIL  __tests__/api.spec.js (5.478s)
  Posts
    ? should return all posts and first post should have comments (5251ms)

  ● Posts ? should return all posts and first post should have comments

    ValidationError: child "name" fails because ["name" must be a number]

      at Object.<anonymous>.exports.process (node_modules/joi/lib/errors.js:152:19)
      at Object.<anonymous>.internals.Object.Object.<anonymous>.internals.Any._validateWithOptions (node_modules/joi/lib/any.js:633:27)
      at Object.<anonymous>.module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:104:23)
      at jsonTypesAssertion (node_modules/frisby/src/frisby/expects.js:101:24)
      at node_modules/frisby/src/frisby/utils.js:38:7
      at node_modules/lodash/core.js:1049:13
      at Function.forEach (node_modules/lodash/core.js:1987:12)
      at Object.withPath (node_modules/frisby/src/frisby/utils.js:37:7)
      at FrisbySpec.jsonTypes (node_modules/frisby/src/frisby/expects.js:100:11)
      at FrisbySpec._addExpect (node_modules/frisby/src/frisby/spec.js:396:23)
      at FrisbySpec._runExpects (node_modules/frisby/src/frisby/spec.js:288:24)
      at _fetch.fetch.then.then (node_modules/frisby/src/frisby/spec.js:142:14)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.961s, estimated 6s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by H1Gdev** [comment]
Jest handles [Event: 'unhandledRejection'](https://nodejs.org/api/process.html#process_event_unhandledrejection).

So I think that it is being processed in the following order.

1. Timeout occurred.
2. Finish test spec.
3. Unhandled promise rejection.

**Comment by ingshtrom** [comment]
@H1Gdev aaahhhh. well that is interesting. So Jest is properly waiting on it, but the timeout occurs and then things go down the toilet. I think that makes sense, which would mean there isn't anything to do. Just to be aware of this as someone writing tests.

Thank you!
