### ISSUE TITLE
Return promise instead of calling done callback?

### ISSUE THREAD

**Issue by tsongas** [vlucas/frisby#429]
I learned you can chain tests by returning a promise instead of calling a callback, for example

```
it('should not let unauthorized request get user', done => {
  frisby.get('http://' + config.host + '/api/user/1')
  .expect('status', 400)
  .done(done);
});
```
becomes
```
it('should not let unauthorized request get user', () => {
   return frisby.get('http://' + config.host + '/api/user/1')
     .expect('status', 400);
});
```

Seems cleaner than using a callback, however one thing I noticed is that when running multiple spec files I'm getting random, intermittent errors saying ` TypeError: Cannot read property 'validate' of undefined`. These are my only dependencies:

```
  "devDependencies": {
    "frisby": "^2.0.10",
    "jest": "^22.0.4"
  }
```
Could the fact that I'm returning promises instead of calling a callback be causing that error? I've seen previous issues with a similar `TypeError` so I'm not sure what to think....

**Comment by H1Gdev** [comment]
@tsongas 
Do not occur this error in my test environment.
Please tell me your test specs and error detail(message, call stack and more).

**Comment by tsongas** [comment]
Here's an example of a test file that just failed when run along with a bunch of other files:

```
const frisby = require('frisby');
const Joi = frisby.Joi;
const config = require('../../config');

describe('Authenticate endpoint', function() {

  it('should let member log in with credentials', function() {
    return frisby.post('http://' + config.host + '/api/authenticate',
      {'employeeId':config.memberEmployeeId, 'password':config.memberPassword})
      .expect('status', 200)
      .expect('header', 'content-type', /application\/json/)
      .expect('jsonTypes', {
        id: Joi.number(),
        token: Joi.string()
      })
      .expect('json', {
        id: config.memberDatabaseId
      });
  });

  it('should not let member log in without credentials', function() {
    return frisby.post('http://' + config.host + '/api/authenticate',
      {'employeeId':'', 'password':''})
      .expect('status', 403);
  });

});
```
Here is the error:
```
> test@1.0.0 test /home/ubuntu/workspace/test
> jest __tests__/api/

 PASS  __tests__/api/user_spec.js
 PASS  __tests__/api/users_spec.js
 PASS  __tests__/api/cases_spec.js
 PASS  __tests__/api/case_spec.js
 PASS  __tests__/api/note_spec.js
 PASS  __tests__/api/home_spec.js
 PASS  __tests__/api/providers_spec.js
 FAIL  __tests__/api/authenticate_spec.js
  ● Authenticate endpoint › should let member log in with credentials

    TypeError: Cannot read property 'validate' of undefined
      
      at Object.internals.checkOptions (node_modules/joi/lib/any.js:36:35)
      at internals.Any._validateWithOptions (node_modules/joi/lib/any.js:628:19)
      at root.validate (node_modules/joi/lib/index.js:104:23)
      at jsonTypesAssertion (node_modules/frisby/src/frisby/expects.js:104:24)
      at node_modules/frisby/src/frisby/utils.js:38:7
      at node_modules/lodash/core.js:1049:13
      at Function.forEach (node_modules/lodash/core.js:1987:12)
      at Object.withPath (node_modules/frisby/src/frisby/utils.js:37:7)
      at FrisbySpec.jsonTypes (node_modules/frisby/src/frisby/expects.js:103:11)
      at FrisbySpec._addExpect.e (node_modules/frisby/src/frisby/spec.js:368:23)
      at FrisbySpec._runExpects (node_modules/frisby/src/frisby/spec.js:260:24)
      at _fetch.fetch.then.then.responseBody (node_modules/frisby/src/frisby/spec.js:139:14)

Test Suites: 1 failed, 7 passed, 8 total
Tests:       1 failed, 56 passed, 57 total
Snapshots:   0 total
Time:        8.812s
Ran all test suites matching /__tests__\/api\//i.
npm ERR! Test failed.  See above for more details.
```
I re-ran that particular file by itself via `jest __tests__/api/authenticate_spec.js` and it passes:
```
> test@1.0.0 test-authenticate /home/ubuntu/workspace/test
> jest __tests__/api/authenticate_spec.js

 PASS  __tests__/api/authenticate_spec.js
  Authenticate endpoint
    ✓ should let member log in with credentials (182ms)
    ✓ should not let member log in without credentials (77ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.576s
Ran all test suites matching /__tests__\/api\/authenticate_spec.js/i.
```
Then, I re-ran the entire test suite and everything passed. So, an intermittent problem.

**Comment by H1Gdev** [comment]
@tsongas
I think that **it()** has done termination processing.

My suggestion is that adjust Jasmine timeout in either way.(default: 5[ms])

- set jasmine.DEFAULT_TIMEOUT_INTERVAL.
- set 3rd argument in it().

https://jasmine.github.io/api/2.6/global.html#it
