### ISSUE TITLE
TypeError: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by koooge** [vlucas/frisby#455]
hi there. I encountered an issue at `expect('jsonTypes', '*', {foo: Joi.number(). bar: Joi.string()})`.
Joi.validate seems to be undefined occasionally.

```
    TypeError: Cannot read property 'validate' of undefined

      at Object.<anonymous>.internals.Object.checkOptions (node_modules/joi/lib/types/any/index.js:94:40)
      at Object.<anonymous>.internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:663:18)
      at Object.<anonymous>.module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:139:23)
      at jsonTypesAssertion (node_modules/frisby/src/frisby/expects.js:109:24)
      at _.each.jsonChunk (node_modules/frisby/src/frisby/utils.js:75:7)
      at arrayEach (node_modules/lodash/lodash.js:508:11)
      at Function.forEach (node_modules/lodash/lodash.js:9334:14)
      at Object.withPath (node_modules/frisby/src/frisby/utils.js:74:7)
      at FrisbySpec.jsonTypes (node_modules/frisby/src/frisby/expects.js:108:11)
      at FrisbySpec._addExpect.response (node_modules/frisby/src/frisby/spec.js:388:23)
      at FrisbySpec._runExpects (node_modules/frisby/src/frisby/spec.js:282:24)
      at _fetch.fetch.Promise.resolve.then.then.then (node_modules/frisby/src/frisby/spec.js:89:14)
```

**Comment by H1Gdev** [comment]
Please adjust Jasmine timeout.(refer to #429.)

**Comment by koooge** [comment]
okay thanks for your quick response
