### ISSUE TITLE
`.expect('jsonTypes', '*', {})` does not allow an empty array

### ISSUE THREAD

**Issue by koooge** [vlucas/frisby#462]
Hi there.  😸 
`.expect('jsonTypes', '*', {})` does not allow an empty array. But API which returns array of objects usually returns `[]` even when the array has no object.
So, I think `.expect('jsonTypes', '*', {})`  should allow `[]`.
what do you think about this?

test code
```
const frisby = require('frisby'),
	Joi = frisby.Joi;

it('should pass', (done) => {
  frisby.fromJSON([])
    .inspectBody()
    .expect('jsonTypes', '*', {
      foo: Joi.string()
    })
    .done(done);
});
```

```
> jest

 FAIL  ./hoge.spec.js
  ✕ should pass (25ms)

  ● should pass

    Expected '*' not found (path '*')

      at _.each.segment (node_modules/frisby/src/frisby/utils.js:48:13)
      at arrayEach (node_modules/lodash/lodash.js:508:11)
      at Function.forEach (node_modules/lodash/lodash.js:9334:14)
      at Object.withPath (node_modules/frisby/src/frisby/utils.js:16:5)
      at FrisbySpec.jsonTypes (node_modules/frisby/src/frisby/expects.js:108:11)
      at response (node_modules/frisby/src/frisby/spec.js:376:23)
      at _fetch._fetch.then.response (node_modules/frisby/src/frisby/spec.js:217:34)

  console.log node_modules/frisby/src/frisby/spec.js:326

    Body: []

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
```

fyi) my workaround

```
it('should pass', (done) => {
  frisby.fromJSON([])
    .inspectBody()
    .expect('jsonTypes', Joi.array().items({
      foo: Joi.string()
    })
    .done(done);
});
```

**Comment by vlucas** [comment]
The error message could be improved, but technically the test is not wrong. There are no objects that exist when you are trying to run assertions on them.

**Comment by H1Gdev** [comment]
This error message outputs if no object exists in path.
(It is not an error message specialized for Array.)

format is
```
Expected '<SEGMENT>' not found (path '<PATH>')
```
