### ISSUE TITLE
Could not generate token using frisby v2

### ISSUE THREAD

**Issue by G4gan** [vlucas/frisby#561]
i am using frisby for apis automation and Jasmine for test. I am not able to generate simple token generation using basic Auth

this is how my curl call look like for token generation and same I am trying with Frisby.js.
`$ curl -k  https://URL -u username:password -H "header:value" `

The output brings token like some value
`TDIKhjglj7698ssjgljuypubvbi`

Same I am doing with frisby to generate token so in this case I am not getting error and my spec is getting passed everytime. Even for negative expects conditions. **here is my code**

`var frisby =require('frisby');`
`frisby.globalSetup({`
`request: {`
 ` headers: {`

   `'Authorization': 'Basic ' + Buffer.from("username:password").toString('base64'),`
`    'Content-Type': 'application/json+scim',`
 `   'header':'value'`
`}}
 });`

` //do setup for Authorization of the token for REST call`
`it ('uses globalSetup for every test after it is called', function () {`

    `return frisby
     .get('URL')`
      ` .inspectResponse()`
      .expect('status', 400),`
      { strictSSL: false }`
      });`

can anyone just point out what exactly am I missing in code. I have tested with response 400 still test is getting passed and token not getting generated. I am using link [Frisby Documentation](https://docs.frisbyjs.com/api-and-usage/setup)

Also running test using -

`#jasmine test_spec.js`
`Randomized with seed 54594`
`Started`

`1 spec, 0 failures`
`Finished in 0.049 seconds`
`Randomized with seed 54594 (jasmine --random=true --seed=54594)`

**Comment by vlucas** [comment]
Try using `inspectRequest()` to ensure that the header values are getting passed correctly, and are the values that you expect.

**Comment by G4gan** [comment]
Thanks @vlucas.

**Comment by LarryBattleWork** [comment]
Your curl command disables HTTPS cert checking with the `-k` flag.
So maybe you need to do the same in the frisby test. 
Just guessing but maybe you should add the `node-fetch` options to disable HTTPS cert checking.
Try this.

```js
var frisby = require('frisby');
frisby.globalSetup({
    request: {
        headers: {
            'Authorization': 'Basic ' + Buffer.from("username:password").toString('base64'),
            'header':'value'
        },
        // It's one of these
        strictSSL : false,
        rejectUnauthorized: false
    } 
});

//do setup for Authorization of the token for REST call
it ('uses globalSetup for every test after it is called', function () {
    return frisby.get('URL')
        .inspectResponse()
        .expect('status', 400);
});
```

**Comment by G4gan** [comment]
@LarryBattleWork 
Getting error when passing either of strictSSL : false, rejectUnauthorized: false in globalSetup()
Failures:
    **FetchError: request to http://URL/login failed, reason: socket hang up**
  Stack:
    error properties: null({ type: 'system', errno: 'ECONNRESET', code: 'ECONNRESET', constructor: Function })
        at <Jasmine>
        at ClientRequest.<anonymous> (dir\node_modules\node-fetch\lib\index.js:1455:11)
        at ClientRequest.emit (events.js:310:20)

**Comment by G4gan** [comment]
Thanks. 
It worked using adding above globaSetup().
**process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";**

**Comment by LarryBattleWork** [comment]
So your solution looks like this?

```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

frisby.globalSetup({
    request: {
        headers: {
            'Authorization': 'Basic ' + Buffer.from("username:password").toString('base64'),
            'header':'value'
        }
    } 
});
```
NOTE: Don't use `NODE_TLS_REJECT_UNAUTHORIZED` in production code.
Doc link: https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value

**Comment by G4gan** [comment]
@LarryBattleWork thanks for response.
Can you suggest other property other than this which will work.
I tried 
strictSSL : false,
rejectUnauthorized: false
Both seems to not work.

Also how can I get the response in variable.
I tried 
.then(function (res) {
let postId = res.json;
Console.log(postId)
}
But this seems to give error.
Any suggestions.

**Comment by H1Gdev** [comment]
If curl `-k` option is removed, does it give an error like frisby ?

**Comment by G4gan** [comment]
@H1Gdev 
-k in curl is for verifying server legitimacy.
so in that case it error me with ssl error.

**Comment by G4gan** [comment]
@vlucas Can you please suggest which reporting goes with Jasmine-Frisby project.
Or if any links yo can refer me too.

Thanks in advance.
